#!/bin/sh
# etcd database backup

# 节点m1的恢复如下
ETCDCTL_API=3 etcdctl snapshot restore snapshot.db --name m1 \
--initial-cluster m1=http://host1:2380,m2=http://host2:2380,m3=http://host3:2380 \
--initial-cluster-token etcd-cluster-1 \
--initial-advertise-peer-urls https://host1:2380

