#!/bin/sh

cd ~

yum install unzip -y

if [ $? -eq 0 ]
then
    wget https://releases.hashicorp.com/consul/1.4.0/consul_1.4.0_linux_amd64.zip
    if [ $? -ne 0 ]
    then
        echo "download consul failed\n"
        exit
    fi

    unzip consul_1.4.0_linux_amd64.zip
    if [ $? -ne 0 ]
    then
        echo "unzip consul.zip failed\n"
        exit
    fi

    cp -a consul /usr/bin
    if [ $? -ne 0 ]
    then
        echo "copy consul to /usr/bin failed\n"
        exit
    fi

    consul -v
    if [ $? -ne 0 ]
    then
        echo "install consul failed!\n"
        exit
    fi
        echo "install consul success!\n"
else
    echo "install unzip failed\n"
fi


